name: CodSpeed Benchmarks
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Download available input files
        env:
          ADVENT_OF_CODE_SESSION: ${{ secrets.AOC_SESSION }}
        run: |
          mkdir -p inputs
          for i in {1..25}; do
            aoc download -I -i inputs/day$i.txt --year 2024 -d $i || true
          done

      - name: Build the benchmark target(s)
        run: cargo codspeed build

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}