name: CodSpeed Benchmarks
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: AoC-badges
        uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: 2051065
          session: ${{ secrets.AOC_SESSION }}

      - uses: stefanzweifel/git-auto-commit-action@v4     # Step that pushes these local changes back to your github repo
        with:
          commit_message: Update badges
          file_pattern: README.md

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        with:
          cache-target: release
          bins: cargo-codspeed, aoc-cli

      - name: Download available input files
        env:
          ADVENT_OF_CODE_SESSION: ${{ secrets.AOC_SESSION }}
        run: |
          mkdir -p inputs
          for i in {1..25}; do
            aoc download -I -i inputs/day$i.txt --year 2024 -d $i || true
          done

      - name: Build the benchmark target(s)
        run: cargo codspeed build

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}